name: dalel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  awesome_dialog: ^3.2.1
  google_sign_in: ^6.2.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  firebase_messaging: ^15.0.3
  flutter_facebook_auth: ^7.0.1
  rive_common: ^0.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
